# Generated by Django 5.0.4 on 2024-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fist_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='Store_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='store_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
