# Generated by Django 5.0.4 on 2024-04-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_register_rename_email_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='userPassword',
        ),
    ]
