# Generated by Django 5.0.4 on 2024-04-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_shoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registration',
        ),
    ]
